export enum SocketServerEventNames {
    CreateGame = 'createGame',
    DevGameStatus = 'devGameStatus',
    JoinGame = 'joinGame',
    Move = 'move',
    ToggleDoorState = 'toggleDoorState',
    StartFight = 'startFight',
    ExecuteAttack = 'executeAttack',
    AttemptEscape = 'attempEscape',
    EndTurn = 'endTurn',
    ToggleDebugMode = 'toggleDebugMode',
    DeactivateDebugMode = 'deactivateDebugMode',
    Teleport = 'teleport',
    UseTeleporter = 'use-teleporter',
    HandleTrap = 'handleTrap',
    PickUpItem = 'pickUpItem',
    DropItem = 'dropItem',
    GetActivePlayer = 'getActivePlayer',
    GetGameState = 'getGameState',
}

export enum SocketClientEventNames {
    StartGame = 'startGame',
    MovePlayer = 'movePlayer',
    MovementOver = 'movementOver',
    ChangeActivePlayer = 'changeActivePlayer',
    ToggleDoorState = 'toggleDoorState',
    StartFight = 'startFight',
    ProcessAttack = ' processAttack',
    SwitchTurn = ' switchTurn',
    ServerError = 'serverError',
    ProcessEscapeAttempt = 'processEscapeAttempt',
    EndFight = 'endFight',
    EndTurn = 'endTurn',
    Clock = 'gameClock',
    StartTurn = 'startTurn',
    EndGame = 'endGame',
    UpdateGame = 'updateGame',
    ShowEndFightNotification = 'showEndFightNotificaiton',
    TrapEncountered = 'trapEncountered',
    TrapResolved = 'trapResolved',
    ToggleDebugMode = 'toggleDebugMode',
    DeactivateDebugMode = 'deactivateDebugMode',
    Teleport = 'teleport',
    PickUpItem = 'pickUpItem',
    DropItem = 'dropItem',
    GetActivePlayer = 'getActivePlayer',
    GameState = 'gameState',
}

export enum SocketEventNames {
    GetCurrentGamePreviews = 'getCurrentGamePreviews',
    ChatHistory = 'chatHistory',
    CurrentGamePreviewsUpdated = 'currentGamePreviewsUpdated',
}
